{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tmvkrpxl0",
    "module": "krangemap",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.2.jar",
          "url": "krangemap-1.2.jar",
          "size": 90139,
          "sha512": "2b8d7d59b37d8e1a2c5c0ca401ad4308cd075cab522896aced99964e58f94a8f9a9f8aa5c65dcd0e4fd8bf9bae2f755e84d7cc4ee1eced9cfdc5175e17e87a14",
          "sha256": "656c64d5f403ef837c2f59d5ef1257b1632707c9682fb5c3b12371e26fca0e5e",
          "sha1": "c37d313caa7209585c0e14928e200a8240dd0426",
          "md5": "53bb4d0a568e8bcb0ff7f0f55140adac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "Srg2Source",
          "version": {
            "requires": "8.0.8"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.11"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.2.jar",
          "url": "krangemap-1.2.jar",
          "size": 90139,
          "sha512": "2b8d7d59b37d8e1a2c5c0ca401ad4308cd075cab522896aced99964e58f94a8f9a9f8aa5c65dcd0e4fd8bf9bae2f755e84d7cc4ee1eced9cfdc5175e17e87a14",
          "sha256": "656c64d5f403ef837c2f59d5ef1257b1632707c9682fb5c3b12371e26fca0e5e",
          "sha1": "c37d313caa7209585c0e14928e200a8240dd0426",
          "md5": "53bb4d0a568e8bcb0ff7f0f55140adac"
        }
      ]
    }
  ]
}
