{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tmvkrpxl0",
    "module": "krangemap",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.1.jar",
          "url": "krangemap-1.1.jar",
          "size": 87483,
          "sha512": "ec8706f33115a4f91733267f91aefb4f7f204edf238d82e02fe57a123be0f8ddeb7d796222e613f91c45046cb1ac1ea22e10bb90a003cf42c823a774ad7ed94c",
          "sha256": "d4d6a885d45b88819512d79253b9e1cbdd1338ddf32863599c4e9b75ca4b1da1",
          "sha1": "5edb8ab1781c2e0ce7a3229e55e26daf8c932173",
          "md5": "a424a88d8a6484bc1ef34797a02b4aed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "Srg2Source",
          "version": {
            "requires": "8.0.8"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.11"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.1.jar",
          "url": "krangemap-1.1.jar",
          "size": 87483,
          "sha512": "ec8706f33115a4f91733267f91aefb4f7f204edf238d82e02fe57a123be0f8ddeb7d796222e613f91c45046cb1ac1ea22e10bb90a003cf42c823a774ad7ed94c",
          "sha256": "d4d6a885d45b88819512d79253b9e1cbdd1338ddf32863599c4e9b75ca4b1da1",
          "sha1": "5edb8ab1781c2e0ce7a3229e55e26daf8c932173",
          "md5": "a424a88d8a6484bc1ef34797a02b4aed"
        }
      ]
    }
  ]
}
