{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tmvkrpxl0",
    "module": "krangemap",
    "version": "1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.5.jar",
          "url": "krangemap-1.5.jar",
          "size": 90027,
          "sha512": "bf640f300e27a7e41df3cc23f3ad531ed814a508e3c7ecb4126c4fb182e7129c61b63a104c0ba0a87a84fa9fa21ec3ec88685595734c53686dd8b05878e4133e",
          "sha256": "8e5a583ad11ac304d17fa84f771245e4581b084f5c481f7cb0f6228e8dcf3036",
          "sha1": "35704fe77ec24d8351dfa10e9bb0da35804962e3",
          "md5": "8809d9b30218da63dd1922e0445417cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "Srg2Source",
          "version": {
            "requires": "8.0.8"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.5.jar",
          "url": "krangemap-1.5.jar",
          "size": 90027,
          "sha512": "bf640f300e27a7e41df3cc23f3ad531ed814a508e3c7ecb4126c4fb182e7129c61b63a104c0ba0a87a84fa9fa21ec3ec88685595734c53686dd8b05878e4133e",
          "sha256": "8e5a583ad11ac304d17fa84f771245e4581b084f5c481f7cb0f6228e8dcf3036",
          "sha1": "35704fe77ec24d8351dfa10e9bb0da35804962e3",
          "md5": "8809d9b30218da63dd1922e0445417cd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "krangemap-1.5-fatJar.jar",
          "url": "krangemap-1.5-fatJar.jar",
          "size": 74519992,
          "sha512": "5f82d7544222cbea8285e327dceb654501c8f11b04a64a690d6cff957306470a7eec645df4d522b5e3dbcaa178d7524953de2fec4b89b02223f0daed18ba0a45",
          "sha256": "84c72ed91567fb4960fcb63c7fd2d12f3a88bd765b8529ab60dfdf41c5657345",
          "sha1": "69fff453b51b6f262a21f4a61258cf8c5ab4f1ed",
          "md5": "5422f5d1ec87c4e7fe892d27f89a7abb"
        }
      ]
    }
  ]
}
