{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tmvkrpxl0",
    "module": "krangemap",
    "version": "1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.5.jar",
          "url": "krangemap-1.5.jar",
          "size": 90053,
          "sha512": "d2863da075cedbc68e69a7b4077070d024196321b78e0f08cc15fa2f52f8f459f9e405bea3e5a68de164d2ef51c7d8b4a88fc0928325730d827d12d8a4efb9dd",
          "sha256": "b10903883a7c2aa7c12e924778cd5f4cd6e6f57101483472f7e6928275c54f68",
          "sha1": "be27adb8d7a21b019ad3b2cfbdfc597c5cfd7d97",
          "md5": "54de6d6dcd0c3eeeee8e9175a7b94604"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "Srg2Source",
          "version": {
            "requires": "8.0.8"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.5.jar",
          "url": "krangemap-1.5.jar",
          "size": 90053,
          "sha512": "d2863da075cedbc68e69a7b4077070d024196321b78e0f08cc15fa2f52f8f459f9e405bea3e5a68de164d2ef51c7d8b4a88fc0928325730d827d12d8a4efb9dd",
          "sha256": "b10903883a7c2aa7c12e924778cd5f4cd6e6f57101483472f7e6928275c54f68",
          "sha1": "be27adb8d7a21b019ad3b2cfbdfc597c5cfd7d97",
          "md5": "54de6d6dcd0c3eeeee8e9175a7b94604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "krangemap-1.5-fatJar.jar",
          "url": "krangemap-1.5-fatJar.jar",
          "size": 74520018,
          "sha512": "99c57ccc4dfaf36e49273d128001d7a5830f099c9115c51482cc59ee1cd4e6d53c22dba63263e21f2468030fbf45871aa925048db2471c94d0d6459217f914cc",
          "sha256": "b1425a4e95aae5f0447b1cb8ee8334c8490274a4e35f1128c7180473f568c083",
          "sha1": "a8c33ef9c6d6120c75857848dd3d7882dd37bc97",
          "md5": "9cd3fb42415526e8ee2b88fae82083e4"
        }
      ]
    }
  ]
}
