{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tmvkrpxl0",
    "module": "krangemap",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.3.jar",
          "url": "krangemap-1.3.jar",
          "size": 90202,
          "sha512": "fe8467e19fc751146465e87287e0aba75a2eac8d61a3fa672cd27a0fe21a066acb6fb068e8819ef4104a09b8d8dd42388349f556929f3e7028fbfab451c52f19",
          "sha256": "59a2c1662b76b6307755a65764fb45b579f2993716ef247cd899f951510bc624",
          "sha1": "6ecfe7aee1bac7d67774a1bb20c0f1a942f0902f",
          "md5": "a982f2197163015b94198db7a7dc51db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "Srg2Source",
          "version": {
            "requires": "8.0.8"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.11"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.3.jar",
          "url": "krangemap-1.3.jar",
          "size": 90202,
          "sha512": "fe8467e19fc751146465e87287e0aba75a2eac8d61a3fa672cd27a0fe21a066acb6fb068e8819ef4104a09b8d8dd42388349f556929f3e7028fbfab451c52f19",
          "sha256": "59a2c1662b76b6307755a65764fb45b579f2993716ef247cd899f951510bc624",
          "sha1": "6ecfe7aee1bac7d67774a1bb20c0f1a942f0902f",
          "md5": "a982f2197163015b94198db7a7dc51db"
        }
      ]
    }
  ]
}
