{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tmvkrpxl0",
    "module": "krangemap",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.4.jar",
          "url": "krangemap-1.4.jar",
          "size": 90263,
          "sha512": "eb178c1bf80ed82d6b576e539a1fa373065731ba2c1b89a35c62f76080ffc7635968e169a199386ea8fb5dc342a2b00d1260a56e497944e45b9275dc68e6b555",
          "sha256": "80f9e772ac360fa5ae42cc5a87a602855989672d78c3bd518d51597bc9383892",
          "sha1": "944a747202a2df16819ba8cad7d954898c63c985",
          "md5": "65d35f41b94bfd279c16a7e497f47f5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "Srg2Source",
          "version": {
            "requires": "8.0.8"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.11"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.4.jar",
          "url": "krangemap-1.4.jar",
          "size": 90263,
          "sha512": "eb178c1bf80ed82d6b576e539a1fa373065731ba2c1b89a35c62f76080ffc7635968e169a199386ea8fb5dc342a2b00d1260a56e497944e45b9275dc68e6b555",
          "sha256": "80f9e772ac360fa5ae42cc5a87a602855989672d78c3bd518d51597bc9383892",
          "sha1": "944a747202a2df16819ba8cad7d954898c63c985",
          "md5": "65d35f41b94bfd279c16a7e497f47f5b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "krangemap-1.4-fatJar.jar",
          "url": "krangemap-1.4-fatJar.jar",
          "size": 74517461,
          "sha512": "b34cf31a038e41546f5585d74a603b759a77ee235ccc3ee753ddf7e10b8a65ffabb308ba4082627ac71410731ea56f4de6dbec0d1e772bf2a81c548f491e5153",
          "sha256": "cff4442b43cb9f988db3144306ab6dec51e20b7a8f4fc69d458dc8f6e79ba23a",
          "sha1": "8a07e04c6c7467d9454dd20383d1132ff31a6594",
          "md5": "425638f338e56367613102cf46d9adcf"
        }
      ]
    }
  ]
}
