{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tmvkrpxl0",
    "module": "krangemap",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.4.jar",
          "url": "krangemap-1.4.jar",
          "size": 90252,
          "sha512": "6b082d6f732502677e2a25136acf5293b1968864d5e1c740ad94d4ed0307180eb97bef5b41c0584ab6f0815e8d22135282d515cbfb3d4a6986bb921f4f1ca9a3",
          "sha256": "818179a2e38182a825223ba12d413da4a0496fabdff9436cb39a5c9ed5727b34",
          "sha1": "214dbaa8ae8f6562e08d99d7f3e2cc1defcb7a9c",
          "md5": "b0ffaa8c66f8fc622e8c12affb983f6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "Srg2Source",
          "version": {
            "requires": "8.0.8"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "krangemap-1.4.jar",
          "url": "krangemap-1.4.jar",
          "size": 90252,
          "sha512": "6b082d6f732502677e2a25136acf5293b1968864d5e1c740ad94d4ed0307180eb97bef5b41c0584ab6f0815e8d22135282d515cbfb3d4a6986bb921f4f1ca9a3",
          "sha256": "818179a2e38182a825223ba12d413da4a0496fabdff9436cb39a5c9ed5727b34",
          "sha1": "214dbaa8ae8f6562e08d99d7f3e2cc1defcb7a9c",
          "md5": "b0ffaa8c66f8fc622e8c12affb983f6b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "krangemap-1.4-fatJar.jar",
          "url": "krangemap-1.4-fatJar.jar",
          "size": 74520217,
          "sha512": "f39beed4545d58bb4963191da913d15d45be2f516d4ea3f0e53a93df0e336d333f7f574d8403a2fd12f4358ac913e9bbb12aaaf1ff48dcf8731b8af634a7cbc5",
          "sha256": "8987d7b73fda933efe65cfda841821f9312c2929dd201abe8493128057f51a69",
          "sha1": "057717d519ecda67cd7bc68380294defe13f7814",
          "md5": "ae170910459ee3d05f21e309c80a8474"
        }
      ]
    }
  ]
}
